### ISSUE TITLE
Advertise training sessions/consult services on help page

### ISSUE THREAD

**Issue by anerogic** [wake-forest-ctsi/i2b2-webclient#11]
@Larisa-Rodgers and I would like to advertise our training sessions/consult services offered by updating the "help" page:

Training and consultations are available on i2b2 and the Data Puller tool at no cost to you. Reach out to [ctsidata@wakehealth.edu](mailto:ctsidata@wakehealth.edu) or visit our [website](https://ctsi.wakehealth.edu/service/data-and-design/data-extraction) for more information.
![57cf1dc0-036f-45b9-b8d1-6b3c89493f88](https://github.com/wake-forest-ctsi/i2b2-webclient/assets/115639911/e324d521-1542-4198-ba80-51dccd03a362)

**Comment by irairavivi** [comment]
@anerogic Please see the screenshot below for how this looks in [dev](https://i2b2.ctsidevopsa1pv.medctr.ad.wfubmc.edu/). Let me know if any other changes need to be made; otherwise, it can be deployed to prod.
<img width="872" alt="image" src="https://github.com/wake-forest-ctsi/i2b2-webclient/assets/20191057/43fe48c1-7bd9-4f71-932d-6510a8500ed8">

**Comment by Larisa-Rodgers** [comment]
@irairavivi  Abby and I think it's great. Please do put into prod. Thank you!

**Comment by irairavivi** [comment]
This has been added to production.

For future reference:
- It is helpful to check the PM_USER_LOGIN table to see if any users are currently logged in before deploying any changes to prod i2b2-webclient.
- The below query can also be used to see if any queries are currently running. (It's helpful to add this to a user defined report to see the day's queries).
```sql
SELECT RI.RESULT_INSTANCE_ID, RI.QUERY_INSTANCE_ID, I.QUERY_MASTER_ID, M.USER_ID, M.NAME, RI.SET_SIZE, TO_CHAR(RI.START_DATE,'DD-MON-YY HH24:MI:SS') AS START_DATE, TO_CHAR(RI.END_DATE,'DD-MON-YY HH24:MI:SS') AS END_DATE, ROUND((SYSDATE - I.START_DATE) * (24*60*60)) AS ELAPSED_TIME_S,  ROUND((RI.END_DATE - I.START_DATE) * (24*60*60)) AS RUN_TIME_S, ST.NAME AS "QUERY STATUS", RT.DESCRIPTION , RI.REAL_SET_SIZE, RI.OBFUSC_METHOD, M.GENERATED_SQL, I.MESSAGE
FROM 
QT_QUERY_RESULT_INSTANCE RI, 
QT_QUERY_STATUS_TYPE ST,
QT_QUERY_MASTER M,
QT_QUERY_RESULT_TYPE RT,
QT_QUERY_INSTANCE I
WHERE 
RI.STATUS_TYPE_ID = ST.STATUS_TYPE_ID
AND RI.QUERY_INSTANCE_ID = I.QUERY_INSTANCE_ID
AND RI.RESULT_TYPE_ID = RT.RESULT_TYPE_ID
AND I.QUERY_MASTER_ID = M.QUERY_MASTER_ID
AND RI.START_DATE >= TRUNC(SYSDATE,'DDD')
--AND ST.NAME = 'PROCESSING'
ORDER BY QUERY_INSTANCE_ID DESC
```
